### ISSUE TITLE
access issue

### ISSUE THREAD

**Issue by amin-nas** [sketch-pm/skpm#12] opened 2017-01-26 17:51 UTC
I installed skpm on my personal laptop without any issues, but cant install it on my work laptop. Attached the log file. Any thoughts on how to get around this?
[npm-debug.log.zip](https://github.com/sketch-pm/skpm/files/733095/npm-debug.log.zip)

**Comment by mathieudutour** [comment] 2017-01-26 18:57
hum the issue is coming from keytar. I found this potentially related issue https://github.com/atom/node-keytar/issues/27. I'll try to see what I can do

**Comment by mathieudutour** [comment] 2017-01-26 19:44
Wait, could it be that you don't have the command line tools installed? (http://osxdaily.com/2014/02/12/install-command-line-tools-mac-os-x/)

**Comment by amin-nas** [comment] 2017-01-26 20:42
![screen shot 2017-01-26 at 3 42 01 pm](https://cloud.githubusercontent.com/assets/491202/22349525/0623f9e6-e3de-11e6-8e9c-604ba669a70d.png)
I assume this means I already got them.

**Comment by mathieudutour** [comment] 2017-04-13 10:50
I made the keytar dependency optional, so this should be fixed now

**Closed by mathieudutour** 2017-04-13 10:50 UTC
Labels: bug
